
package com.mycompany.pardusuygulamaislemleri;

import javax.swing.JOptionPane;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;

import removers.AppimagePackRemover;
import removers.FlatackPackRemover;
import removers.PardusPackRemover;
import removers.SnapPackRemover;

/**
 *
 * @author bismih
 */
public class Ekran extends javax.swing.JFrame {

    String pass = "";

    public Ekran() {
        initComponents();
        //? başta şifre alınıyor
        pass = JOptionPane.showInputDialog(rootPane, "Şifreyi giriniz");
        //? listelerin hazırlanması
        PardusPackRemover.getNativeAppList();
        FlatackPackRemover.getNativeAppList();
        AppimagePackRemover.getNativeAppList();
        SnapPackRemover.getNativeAppList();
        //? listelerin görüntülenmesi
        lst_apps.setModel(PardusPackRemover.model);
        lst_flatpack.setModel(FlatackPackRemover.model);
        lst_appimage.setModel(AppimagePackRemover.model);
        lst_snap.setModel(SnapPackRemover.model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lst_apps = new javax.swing.JList<>();
        bt_sil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_flatpack = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        bt_silFlat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_appimage = new javax.swing.JList<>();
        bt_silAppimage = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_snap = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_silSnap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lst_apps);

        bt_sil.setText("sil");
        bt_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_silActionPerformed(evt);
            }
        });

        jLabel1.setText("Pardus Paketleri");

        jScrollPane2.setViewportView(lst_flatpack);

        jLabel2.setText("Flatpack Paketleri");

        bt_silFlat.setText("sil");
        bt_silFlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_silFlatActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lst_appimage);

        bt_silAppimage.setText("sil");
        bt_silAppimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_silAppimageActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lst_snap);

        jLabel3.setText("Appimage Paketleri");

        jLabel4.setText("Snap Paketleri");

        bt_silSnap.setText("sil");
        bt_silSnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_silSnapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3)
                                                .addGap(18, 18, 18)
                                                .addComponent(bt_silAppimage)
                                                .addGap(90, 90, 90)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(bt_silSnap)
                                                .addContainerGap(88, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(61, 61, 61)
                                                                .addComponent(jLabel3)
                                                                .addGap(348, 348, 348)
                                                                .addComponent(jLabel4))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(bt_sil)
                                                                .addGap(90, 90, 90)
                                                                .addComponent(jScrollPane2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 252,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(bt_silFlat)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1)
                                .addGap(333, 333, 333)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel2)
                                                .addGap(30, 30, 30)
                                                .addComponent(bt_silFlat))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jScrollPane2)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 302,
                                                                Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(bt_sil)))))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bt_silAppimage)
                                                .addGap(85, 85, 85))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(5, 5, 5)
                                                                .addComponent(jLabel4)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(bt_silSnap)
                                                                .addGap(95, 95, 95))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jScrollPane3)
                                                                        .addComponent(jScrollPane4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                271,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(44, 44, 44)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_silActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bt_silActionPerformed
        if (!lst_apps.isSelectionEmpty()) {
            PardusPackRemover.removeNativeApp(lst_apps.getSelectedValue(), pass);

        }
    }// GEN-LAST:event_bt_silActionPerformed

    private void bt_silFlatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bt_silFlatActionPerformed
        if (!lst_flatpack.isSelectionEmpty()) {
            FlatackPackRemover.removeNativeApp(lst_flatpack.getSelectedIndex());
            FlatackPackRemover.getNativeAppList();
        }
    }// GEN-LAST:event_bt_silFlatActionPerformed

    private void bt_silAppimageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bt_silAppimageActionPerformed
        if (!lst_appimage.isSelectionEmpty()) {
            AppimagePackRemover.removeNativeApp(lst_appimage.getSelectedIndex());
            AppimagePackRemover.getNativeAppList();
        }
    }// GEN-LAST:event_bt_silAppimageActionPerformed

    private void bt_silSnapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bt_silSnapActionPerformed
        if(!lst_snap.isSelectionEmpty()){
            SnapPackRemover.removeNativeApp(lst_snap.getSelectedIndex(),pass);
            SnapPackRemover.getNativeAppList();
        }
    }// GEN-LAST:event_bt_silSnapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcDarkOrangeIJTheme.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ekran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sil;
    private javax.swing.JButton bt_silAppimage;
    private javax.swing.JButton bt_silFlat;
    private javax.swing.JButton bt_silSnap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lst_appimage;
    private javax.swing.JList<String> lst_apps;
    private javax.swing.JList<String> lst_flatpack;
    private javax.swing.JList<String> lst_snap;
    // End of variables declaration//GEN-END:variables
}
